// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const allergenTable = {
  name: "allergen",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    icon: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    tenantId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const apiKeyCredentialTable = {
  name: "apiKeyCredential",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    principalId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    keyHash: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    revokedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    lastUsedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
  serverName: "api_key_credential",
} as const;
const categoryTable = {
  name: "category",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    icon: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    tenantId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const menuItemTable = {
  name: "menuItem",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    price: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    createdByID: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    tenantId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
  serverName: "menu_item",
} as const;
const menuItemAllergenTable = {
  name: "menuItemAllergen",
  columns: {
    allergenID: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    menuItemID: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["menuItemID", "allergenID"],
  serverName: "menu_item_allergen",
} as const;
const menuItemCategoryTable = {
  name: "menuItemCategory",
  columns: {
    menuItemID: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    categoryID: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["menuItemID", "categoryID"],
  serverName: "menu_item_category",
} as const;
const oauthCredentialTable = {
  name: "oauthCredential",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    principalId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    provider: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    providerId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    email: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    revokedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    lastUsedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
  serverName: "oauth_credential",
} as const;
const passwordCredentialTable = {
  name: "passwordCredential",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    principalId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    email: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    passwordHash: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    passwordSalt: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    revokedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
  serverName: "password_credential",
} as const;
const paymentTable = {
  name: "payment",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    amount: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    notes: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    tenantId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdByID: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    tableID: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const paymentTabItemPaidTable = {
  name: "paymentTabItemPaid",
  columns: {
    paymentID: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    tabItemID: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["paymentID", "tabItemID"],
  serverName: "payment_tab_item_paid",
} as const;
const pinCredentialTable = {
  name: "pinCredential",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    principalId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    tenantId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    staffCode: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    pinHash: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    pinSalt: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    revokedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
  serverName: "pin_credential",
} as const;
const principalTable = {
  name: "principal",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    kind: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    displayName: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    avatarUrl: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    globalCredVersion: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
} as const;
const restaurantSettingsTable = {
  name: "restaurantSettings",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    currencyCode: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    currencyLocale: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    primaryColor: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    secondaryColor: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    timeZone: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    coinsAndNotes: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    tenantId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
  serverName: "restaurant_settings",
} as const;
const restaurantTable = {
  name: "restaurantTable",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    seats: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    closed: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
    },
    closedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    notes: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    tenantId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdById: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    closedById: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
  serverName: "restaurant_table",
} as const;
const roleGrantTable = {
  name: "roleGrant",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    principalId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    scopeKind: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    tenantId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    role: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    grantedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    revokedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    grantedByPrincipalId: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
  serverName: "role_grant",
} as const;
const tabTable = {
  name: "tab",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    locked: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
    },
    closed: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
    },
    closedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    tableID: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    tenantId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdByID: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    closedByID: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const tabItemTable = {
  name: "tabItem",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    notes: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    nameOverride: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    priceOverride: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    readyAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    servedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    tabID: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    menuItemID: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdByID: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    tenantId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
  serverName: "tab_item",
} as const;
const tabItemAllergyRestrictionTable = {
  name: "tabItemAllergyRestriction",
  columns: {
    tabItemID: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    allergenID: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["tabItemID", "allergenID"],
  serverName: "tab_item_allergy_restriction",
} as const;
const tenantTable = {
  name: "tenant",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    slug: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
  },
  primaryKey: ["id"],
} as const;
const allergenRelationships = {
  tenant: [
    {
      sourceField: ["tenantId"],
      destField: ["id"],
      destSchema: "tenant",
      cardinality: "one",
    },
  ],
  menuItems: [
    {
      sourceField: ["id"],
      destField: ["allergenID"],
      destSchema: "menuItemAllergen",
      cardinality: "many",
    },
  ],
  tabItemRestrictions: [
    {
      sourceField: ["id"],
      destField: ["allergenID"],
      destSchema: "tabItemAllergyRestriction",
      cardinality: "many",
    },
  ],
} as const;
const apiKeyCredentialRelationships = {
  principal: [
    {
      sourceField: ["principalId"],
      destField: ["id"],
      destSchema: "principal",
      cardinality: "one",
    },
  ],
} as const;
const categoryRelationships = {
  tenant: [
    {
      sourceField: ["tenantId"],
      destField: ["id"],
      destSchema: "tenant",
      cardinality: "one",
    },
  ],
  menuItems: [
    {
      sourceField: ["id"],
      destField: ["categoryID"],
      destSchema: "menuItemCategory",
      cardinality: "many",
    },
  ],
} as const;
const menuItemAllergenRelationships = {
  menuItem: [
    {
      sourceField: ["menuItemID"],
      destField: ["id"],
      destSchema: "menuItem",
      cardinality: "one",
    },
  ],
  allergen: [
    {
      sourceField: ["allergenID"],
      destField: ["id"],
      destSchema: "allergen",
      cardinality: "one",
    },
  ],
} as const;
const menuItemCategoryRelationships = {
  menuItem: [
    {
      sourceField: ["menuItemID"],
      destField: ["id"],
      destSchema: "menuItem",
      cardinality: "one",
    },
  ],
  category: [
    {
      sourceField: ["categoryID"],
      destField: ["id"],
      destSchema: "category",
      cardinality: "one",
    },
  ],
} as const;
const menuItemRelationships = {
  tenant: [
    {
      sourceField: ["tenantId"],
      destField: ["id"],
      destSchema: "tenant",
      cardinality: "one",
    },
  ],
  createdBy: [
    {
      sourceField: ["createdByID"],
      destField: ["id"],
      destSchema: "principal",
      cardinality: "one",
    },
  ],
  categories: [
    {
      sourceField: ["id"],
      destField: ["menuItemID"],
      destSchema: "menuItemCategory",
      cardinality: "many",
    },
  ],
  allergens: [
    {
      sourceField: ["id"],
      destField: ["menuItemID"],
      destSchema: "menuItemAllergen",
      cardinality: "many",
    },
  ],
  tabItems: [
    {
      sourceField: ["id"],
      destField: ["menuItemID"],
      destSchema: "tabItem",
      cardinality: "many",
    },
  ],
} as const;
const oauthCredentialRelationships = {
  principal: [
    {
      sourceField: ["principalId"],
      destField: ["id"],
      destSchema: "principal",
      cardinality: "one",
    },
  ],
} as const;
const passwordCredentialRelationships = {
  principal: [
    {
      sourceField: ["principalId"],
      destField: ["id"],
      destSchema: "principal",
      cardinality: "one",
    },
  ],
} as const;
const paymentRelationships = {
  tenant: [
    {
      sourceField: ["tenantId"],
      destField: ["id"],
      destSchema: "tenant",
      cardinality: "one",
    },
  ],
  createdBy: [
    {
      sourceField: ["createdByID"],
      destField: ["id"],
      destSchema: "principal",
      cardinality: "one",
    },
  ],
  table: [
    {
      sourceField: ["tableID"],
      destField: ["id"],
      destSchema: "restaurantTable",
      cardinality: "one",
    },
  ],
  tabItems: [
    {
      sourceField: ["id"],
      destField: ["paymentID"],
      destSchema: "paymentTabItemPaid",
      cardinality: "many",
    },
  ],
} as const;
const paymentTabItemPaidRelationships = {
  payment: [
    {
      sourceField: ["paymentID"],
      destField: ["id"],
      destSchema: "payment",
      cardinality: "one",
    },
  ],
  tabItem: [
    {
      sourceField: ["tabItemID"],
      destField: ["id"],
      destSchema: "tabItem",
      cardinality: "one",
    },
  ],
} as const;
const pinCredentialRelationships = {
  principal: [
    {
      sourceField: ["principalId"],
      destField: ["id"],
      destSchema: "principal",
      cardinality: "one",
    },
  ],
  tenant: [
    {
      sourceField: ["tenantId"],
      destField: ["id"],
      destSchema: "tenant",
      cardinality: "one",
    },
  ],
} as const;
const principalRelationships = {
  pinCredentials: [
    {
      sourceField: ["id"],
      destField: ["principalId"],
      destSchema: "pinCredential",
      cardinality: "many",
    },
  ],
  passwordCredentials: [
    {
      sourceField: ["id"],
      destField: ["principalId"],
      destSchema: "passwordCredential",
      cardinality: "many",
    },
  ],
  oauthCredentials: [
    {
      sourceField: ["id"],
      destField: ["principalId"],
      destSchema: "oauthCredential",
      cardinality: "many",
    },
  ],
  apiKeyCredentials: [
    {
      sourceField: ["id"],
      destField: ["principalId"],
      destSchema: "apiKeyCredential",
      cardinality: "many",
    },
  ],
  roleGrants: [
    {
      sourceField: ["id"],
      destField: ["principalId"],
      destSchema: "roleGrant",
      cardinality: "many",
    },
  ],
  grantedRoles: [
    {
      sourceField: ["id"],
      destField: ["grantedByPrincipalId"],
      destSchema: "roleGrant",
      cardinality: "many",
    },
  ],
  createdMenuItems: [
    {
      sourceField: ["id"],
      destField: ["createdByID"],
      destSchema: "menuItem",
      cardinality: "many",
    },
  ],
  createdTabs: [
    {
      sourceField: ["id"],
      destField: ["createdByID"],
      destSchema: "tab",
      cardinality: "many",
    },
  ],
  closedTabs: [
    {
      sourceField: ["id"],
      destField: ["closedByID"],
      destSchema: "tab",
      cardinality: "many",
    },
  ],
  createdRestaurantTables: [
    {
      sourceField: ["id"],
      destField: ["createdById"],
      destSchema: "restaurantTable",
      cardinality: "many",
    },
  ],
  closedRestaurantTables: [
    {
      sourceField: ["id"],
      destField: ["closedById"],
      destSchema: "restaurantTable",
      cardinality: "many",
    },
  ],
  createdPayments: [
    {
      sourceField: ["id"],
      destField: ["createdByID"],
      destSchema: "payment",
      cardinality: "many",
    },
  ],
} as const;
const restaurantSettingsRelationships = {
  tenant: [
    {
      sourceField: ["tenantId"],
      destField: ["id"],
      destSchema: "tenant",
      cardinality: "one",
    },
  ],
} as const;
const restaurantTableRelationships = {
  tenant: [
    {
      sourceField: ["tenantId"],
      destField: ["id"],
      destSchema: "tenant",
      cardinality: "one",
    },
  ],
  createdBy: [
    {
      sourceField: ["createdById"],
      destField: ["id"],
      destSchema: "principal",
      cardinality: "one",
    },
  ],
  closedBy: [
    {
      sourceField: ["closedById"],
      destField: ["id"],
      destSchema: "principal",
      cardinality: "one",
    },
  ],
  tabs: [
    {
      sourceField: ["id"],
      destField: ["tableID"],
      destSchema: "tab",
      cardinality: "many",
    },
  ],
  payments: [
    {
      sourceField: ["id"],
      destField: ["tableID"],
      destSchema: "payment",
      cardinality: "many",
    },
  ],
} as const;
const roleGrantRelationships = {
  principal: [
    {
      sourceField: ["principalId"],
      destField: ["id"],
      destSchema: "principal",
      cardinality: "one",
    },
  ],
  tenant: [
    {
      sourceField: ["tenantId"],
      destField: ["id"],
      destSchema: "tenant",
      cardinality: "one",
    },
  ],
  grantedBy: [
    {
      sourceField: ["grantedByPrincipalId"],
      destField: ["id"],
      destSchema: "principal",
      cardinality: "one",
    },
  ],
} as const;
const tabItemAllergyRestrictionRelationships = {
  tabItem: [
    {
      sourceField: ["tabItemID"],
      destField: ["id"],
      destSchema: "tabItem",
      cardinality: "one",
    },
  ],
  allergen: [
    {
      sourceField: ["allergenID"],
      destField: ["id"],
      destSchema: "allergen",
      cardinality: "one",
    },
  ],
} as const;
const tabItemRelationships = {
  tenant: [
    {
      sourceField: ["tenantId"],
      destField: ["id"],
      destSchema: "tenant",
      cardinality: "one",
    },
  ],
  tab: [
    {
      sourceField: ["tabID"],
      destField: ["id"],
      destSchema: "tab",
      cardinality: "one",
    },
  ],
  menuItem: [
    {
      sourceField: ["menuItemID"],
      destField: ["id"],
      destSchema: "menuItem",
      cardinality: "one",
    },
  ],
  createdBy: [
    {
      sourceField: ["createdByID"],
      destField: ["id"],
      destSchema: "principal",
      cardinality: "one",
    },
  ],
  allergyRestrictions: [
    {
      sourceField: ["id"],
      destField: ["tabItemID"],
      destSchema: "tabItemAllergyRestriction",
      cardinality: "many",
    },
  ],
  payments: [
    {
      sourceField: ["id"],
      destField: ["tabItemID"],
      destSchema: "paymentTabItemPaid",
      cardinality: "many",
    },
  ],
} as const;
const tabRelationships = {
  tenant: [
    {
      sourceField: ["tenantId"],
      destField: ["id"],
      destSchema: "tenant",
      cardinality: "one",
    },
  ],
  createdBy: [
    {
      sourceField: ["createdByID"],
      destField: ["id"],
      destSchema: "principal",
      cardinality: "one",
    },
  ],
  closedBy: [
    {
      sourceField: ["closedByID"],
      destField: ["id"],
      destSchema: "principal",
      cardinality: "one",
    },
  ],
  table: [
    {
      sourceField: ["tableID"],
      destField: ["id"],
      destSchema: "restaurantTable",
      cardinality: "one",
    },
  ],
  items: [
    {
      sourceField: ["id"],
      destField: ["tabID"],
      destSchema: "tabItem",
      cardinality: "many",
    },
  ],
} as const;
const tenantRelationships = {
  restaurantSettings: [
    {
      sourceField: ["id"],
      destField: ["tenantId"],
      destSchema: "restaurantSettings",
      cardinality: "one",
    },
  ],
  pinCredentials: [
    {
      sourceField: ["id"],
      destField: ["tenantId"],
      destSchema: "pinCredential",
      cardinality: "many",
    },
  ],
  roleGrants: [
    {
      sourceField: ["id"],
      destField: ["tenantId"],
      destSchema: "roleGrant",
      cardinality: "many",
    },
  ],
  restaurantTables: [
    {
      sourceField: ["id"],
      destField: ["tenantId"],
      destSchema: "restaurantTable",
      cardinality: "many",
    },
  ],
  categories: [
    {
      sourceField: ["id"],
      destField: ["tenantId"],
      destSchema: "category",
      cardinality: "many",
    },
  ],
  allergens: [
    {
      sourceField: ["id"],
      destField: ["tenantId"],
      destSchema: "allergen",
      cardinality: "many",
    },
  ],
  menuItems: [
    {
      sourceField: ["id"],
      destField: ["tenantId"],
      destSchema: "menuItem",
      cardinality: "many",
    },
  ],
  tabs: [
    {
      sourceField: ["id"],
      destField: ["tenantId"],
      destSchema: "tab",
      cardinality: "many",
    },
  ],
  tabItems: [
    {
      sourceField: ["id"],
      destField: ["tenantId"],
      destSchema: "tabItem",
      cardinality: "many",
    },
  ],
  payments: [
    {
      sourceField: ["id"],
      destField: ["tenantId"],
      destSchema: "payment",
      cardinality: "many",
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    allergen: allergenTable,
    apiKeyCredential: apiKeyCredentialTable,
    category: categoryTable,
    menuItem: menuItemTable,
    menuItemAllergen: menuItemAllergenTable,
    menuItemCategory: menuItemCategoryTable,
    oauthCredential: oauthCredentialTable,
    passwordCredential: passwordCredentialTable,
    payment: paymentTable,
    paymentTabItemPaid: paymentTabItemPaidTable,
    pinCredential: pinCredentialTable,
    principal: principalTable,
    restaurantSettings: restaurantSettingsTable,
    restaurantTable: restaurantTable,
    roleGrant: roleGrantTable,
    tab: tabTable,
    tabItem: tabItemTable,
    tabItemAllergyRestriction: tabItemAllergyRestrictionTable,
    tenant: tenantTable,
  },
  relationships: {
    allergen: allergenRelationships,
    apiKeyCredential: apiKeyCredentialRelationships,
    category: categoryRelationships,
    menuItemAllergen: menuItemAllergenRelationships,
    menuItemCategory: menuItemCategoryRelationships,
    menuItem: menuItemRelationships,
    oauthCredential: oauthCredentialRelationships,
    passwordCredential: passwordCredentialRelationships,
    payment: paymentRelationships,
    paymentTabItemPaid: paymentTabItemPaidRelationships,
    pinCredential: pinCredentialRelationships,
    principal: principalRelationships,
    restaurantSettings: restaurantSettingsRelationships,
    restaurantTable: restaurantTableRelationships,
    roleGrant: roleGrantRelationships,
    tabItemAllergyRestriction: tabItemAllergyRestrictionRelationships,
    tabItem: tabItemRelationships,
    tab: tabRelationships,
    tenant: tenantRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "allergen" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Allergen = Row<(typeof schema)["tables"]["allergen"]>;
/**
 * Represents a row from the "apiKeyCredential" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ApiKeyCredential = Row<
  (typeof schema)["tables"]["apiKeyCredential"]
>;
/**
 * Represents a row from the "category" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Category = Row<(typeof schema)["tables"]["category"]>;
/**
 * Represents a row from the "menuItem" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type MenuItem = Row<(typeof schema)["tables"]["menuItem"]>;
/**
 * Represents a row from the "menuItemAllergen" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type MenuItemAllergen = Row<
  (typeof schema)["tables"]["menuItemAllergen"]
>;
/**
 * Represents a row from the "menuItemCategory" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type MenuItemCategory = Row<
  (typeof schema)["tables"]["menuItemCategory"]
>;
/**
 * Represents a row from the "oauthCredential" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type OauthCredential = Row<(typeof schema)["tables"]["oauthCredential"]>;
/**
 * Represents a row from the "passwordCredential" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type PasswordCredential = Row<
  (typeof schema)["tables"]["passwordCredential"]
>;
/**
 * Represents a row from the "payment" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Payment = Row<(typeof schema)["tables"]["payment"]>;
/**
 * Represents a row from the "paymentTabItemPaid" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type PaymentTabItemPaid = Row<
  (typeof schema)["tables"]["paymentTabItemPaid"]
>;
/**
 * Represents a row from the "pinCredential" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type PinCredential = Row<(typeof schema)["tables"]["pinCredential"]>;
/**
 * Represents a row from the "principal" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Principal = Row<(typeof schema)["tables"]["principal"]>;
/**
 * Represents a row from the "restaurantSettings" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RestaurantSetting = Row<
  (typeof schema)["tables"]["restaurantSettings"]
>;
/**
 * Represents a row from the "restaurantTable" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RestaurantTable = Row<(typeof schema)["tables"]["restaurantTable"]>;
/**
 * Represents a row from the "roleGrant" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type RoleGrant = Row<(typeof schema)["tables"]["roleGrant"]>;
/**
 * Represents a row from the "tab" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Tab = Row<(typeof schema)["tables"]["tab"]>;
/**
 * Represents a row from the "tabItem" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TabItem = Row<(typeof schema)["tables"]["tabItem"]>;
/**
 * Represents a row from the "tabItemAllergyRestriction" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TabItemAllergyRestriction = Row<
  (typeof schema)["tables"]["tabItemAllergyRestriction"]
>;
/**
 * Represents a row from the "tenant" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Tenant = Row<(typeof schema)["tables"]["tenant"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;
